#information: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - test

jobs:


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
            node-version: 12.x
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: blankmap-front
          heroku_email: junhao.xia@stonybrook.edu
        